on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/benchmark.yml
      - httpie/**/*.py
  pull_request:
    paths:
      - .github/workflows/benchmark.yml
      - httpie/**/*.py

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - id: benchmarks
        name: Run Benchmarks
        run: |
          python -m pip install pyperf
          python extras/profiling/run.py --fresh --complex
